spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/btt_pay
    username: ${DB_USERNAME}
    password: ${DB_PASS}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

# Logging Properties
logging:
  level:
    ROOT: INFO
    com.btt.pay: DEBUG

# JWT Properties
jwt:
  expiration: 28800000

# App Properties
app:
  acct-no-format: 100000000
  trans-no-format: REF10000000